title = "Vergleich BSV <-> Kredit"
version = "1.0.0"

# Tilgungsfeier Darlehen
[interest_only_mortgage]
interest_rate_decimal = 0.045

[bsv]
# Sparphase = saving_phase
# Bausparsumme in Euro
bs_sum = 100000
# Guthabenzins in %
deposit_rates_decimal = 0.01
# Mindeststansparung in %
minimum_saving_amount_decimal = 0.35
# Anschlussgebuehr in %
acquisition_fee_decimal = 0.016
# Ansparzeit in Monaten
saving_time = 120
# Ansparrate monatlich in Euro
saving_rate = 170
# Darlehenphase = loan_phase
#Fest Sollzins in %
fixed_interest_rate_decimal = 0.0249
# Zins- und Tilgungsbeitrag monatlich in %
interest_prinipal_paymants_mounthly_decimal = 0.0035

# Zwischenfinanzierung Ansparung
# Ratenkredit
[instalment_loan]
interest_rate_decimal = 0.08

