title = "Vergleich BSV <-> Kredit"
version = "1.0.0"

# Tilgungsfeier Darlehen
[interest_only_mortgage]
# Sollzins
interest_rate_decimal = 0.045
# Laufzeit
duration_in_months = 120
# Darlehenssumme
loan_amount = 150000

[interest_only_mortage_extension]
# Sollzins
interest_rate_decimal = 0.06

[bsv]
# Sparphase = saving_phase
# Bausparsumme in Euro
bs_sum = 150000
# Guthabenzins in %
deposit_rates_decimal = 0.001
# Mindeststansparung in %
minimum_saving_amount_decimal = 0.35
# Anschlussgebuehr in %
acquisition_fee_decimal = 0.016
# Ansparzeit in Monaten
saving_time = 180
# Ansparzeit separat
one_time_payment = 40000
one_time_payment_moment = 120
# Ansparrate monatlich in Euro
saving_rate = 70
# Darlehenphase = loan_phase
#Fest Sollzins in %
fixed_interest_rate_decimal = 0.0239
# Zins- und Tilgungsbeitrag monatlich in %
interest_prinipal_paymants_mounthly_decimal = 0.005
# Zinsfaktor für Bewertungszahl
interest_factor = 300

# Zwischenfinanzierung Ansparung
# Ratenkredit
[instalment_loan]
interest_rate_decimal = 0.07

# Darlehen ohen BSV
[loan_without_bsv]
interest_rate_forcast_0_10_decimal = 0.045
duration_in_months_0_10 = 120
interest_rate_forcast_11_20_decimal = 0.06
duration_in_months_11_20 = 120
interest_rate_forcast_21_30_decimal = 0.07
duration_in_months_21_30 = 120
interest_rate_forcast_31_40_decimal = 0.07
duration_in_months_31_40 = 120


